Create File-Based Exception Handling
OUTPUT:
Error occurred while processing log: Log file not found: log.txt
File_Based_Exception_Handling.LogProcessingException: Log file not found: log.txt
	at File_Based_Exception_Handling.LogReader.readLogFile(LogReader.java:14)
	at File_Based_Exception_Handling.LogReader.main(LogReader.java:26)
Caused by: java.io.FileNotFoundException: log.txt (The system cannot find the file specified)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:185)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:139)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:109)
	at java.base/java.io.FileReader.<init>(FileReader.java:60)
	at File_Based_Exception_Handling.LogReader.readLogFile(LogReader.java:6)
	... 1 more